info:
  address:
    addressLocality: Amsterdam
    addressRegion: Noord Holland
    alternateName: We hate radio
    description: >-
      We hate radio website
    email: wehateradio@gmail.com
    name: wehateradio.net
  email: wehateradio@gmail.com
header:
  items:
    - links:
        - href: /case-studies
          icon: ['fad', 'graduation-cap']
          title: Case Studies
          titleColor: indigo
        - href: /video
          icon: ['fad', 'video']
          subtitle: Learn how to design with Stoplight
          title: Webinars
          titleColor: yellow
        - divider: true
        - href: /api-design-guide/basics
          icon: ['fad', 'paint-brush']
          subtitle: Learn API Design Best Practices
          title: API Design Guide
          titleColor: green
        - href: /mock-api-guide/basics
          icon: ['fad', 'database']
          subtitle: Create mock API servers
          title: API Mocking Guide
          titleColor: blue
        - href: /api-documentation-guide/basics
          icon: ['fad', 'bookmark']
          subtitle: Learn API Documentation Best Practices
          title: API Documentation Guide
          titleColor: purple
      title: Resources
      width: 300
    - href: /blog
      title: Blog
    - href: /enterprise
      title: Enterprise
    - href: /demo
      isButton: true
      title: Book a Demo
      altBg: purple
    - href: /start
      isButton: true
      title: Start
      icon: ['fad', 'arrow-right']
actionBar:
  ctas:
    - color: white
      href: /demo
      title: Book a Demo
      outlined: true
    - color: purple
      href: 'https://stoplight.io/p/signup'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - links:
        - href: /studio
          title: Design Studio
        - href: /docs
          title: Free Docs
        - href: /hubs
          title: Docs Hubs
        - href: /enterprise
          title: Docs Hubs
      title: Products
    - links:
        - href: /spectral
          title: Spectral
        - href: /prism
          title: Prism
      title: Open Source
    - links:
        - href: /design
          title: API Design
        - href: /documentation
          title: API Documentation
        - href: /mocking
          title: API Mocking
      title: Use Cases
    - links:
        - href: 'https://docs.stoplight.io'
          title: Help Center
        - href: /blog
          title: Blog
        - href: 'https://community.stoplight.io'
          title: 'Forum'
        - href: /webinars
          title: Webinars
        - href: /case-studies
          title: Case Studies
      title: Resources
    - links:
        - href: /about
          title: About Us
        - href: https://stoplight.io/p/roadmap
          title: Roadmap
        - href: 'https://press.stoplight.io'
          title: Press
        - href: /contact-us
          title: Contact Us
        - href: 'https://app.stoplight.io/login'
          title: Classic Login
      title: Company
  legal:
    - href: /privacy
      title: Privacy
    - href: /terms
      title: Terms of Use
    - href: /policy
      title: Policy
  social:
    - href: 'https://twitter.com/stoplightio'
      icon: ['fab', 'twitter']
    - href: 'https://www.linkedin.com/company/stoplight'
      icon: ['fab', 'linkedin']
    - href: 'https://www.github.com/stoplightio'
      icon: ['fab', 'github']
meta:
  description: API Design Management for Teams and Enterprise | Stoplight
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  robots: 'index, follow'
  title: Stoplight
  twitter:
    description: API Design Management for Teams and Enterprise | Stoplight
    image: /images/home-hero.png
    title: Stoplight
    username: '@stoplightio'
  url: 'https://stoplight.io'
customers:
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Deutsche Bank
      src: /images/deutsche_bank.png
    - alt: quicken
      src: /images/customers/quicken.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zendesk
      src: /images/logo_zendesk.png
integrations:
  googleTagManager: GTM-58LWL5P
  hubspot: 4892910
  intercom: g7eo4oae
