info:
  address:
    addressLocality: Amsterdam
    addressRegion: Noord Holland
    alternateName: We hate radio
    description: >-
      We hate radio website
    email: wehateradio@gmail.com
    name: wehateradio.net
  email: wehateradio@gmail.com
# meta:
#   description: API Design Management for Teams and Enterprise | Stoplight
#   favicon: /favicons/favicon.ico
#   image: /images/home-hero.png
#   robots: 'index, follow'
#   title: Stoplight
#   twitter:
#     description: API Design Management for Teams and Enterprise | Stoplight
#     image: /images/home-hero.png
#     title: Stoplight
#     username: '@stoplightio'
#   url: 'https://stoplight.io'
